#!/bin/sh

# main loop to catch them all!
for i in .zshrc .vim .vimrc .screenrc .oh-my-zsh; do
	ln -sf ~/.dotfiles/$i ~/$i || echo "unable to create symlink for $i, eek!"
done

# .ssh files need to be done spiffylike
cd .ssh
./mkauth.sh
test -d ~/.ssh || mkdir -m 0700 ~/.ssh
ln -sf ~/.dotfiles/.ssh/config ~/.ssh/config || echo "unable to create .ssh/config symlink, eek!"
ln -sf ~/.dotfiles/.ssh/authorized_keys ~/.ssh/authorized_keys || echo "unable to create .ssh/authorized_keys symlink, eek!"
cd ..
