#!/bin/bash

# pull in the submodules and set them up
git submodule init
git submodule update

# main loop to catch them all!
shopt -s dotglob
for i in * ; do
	if [[ $i == "." || $i = ".." || $i = "make-symlinks" || $i = ".ssh" \
		|| $i == ".git" || $i == ".gitmodules" || $i == "README" ]]; then
		continue
	fi

	linkpath=`readlink ~/$i`
	if [[ $linkpath == ~/.dotfiles/$i ]]; then
		# move along
		true
	else
		if [[ -e ~/$i ]]; then
			# something is there, what is it?
			if [[ -L "~/$i" ]]; then
				# it's a symlink, but not to the right place!
				echo "~/$i is a symlink, but it's not to the right place (should be ~/.dotfiles/$i"
			else
				# it's just a file, methinks? we'll test it.
				echo "~/$i is an existing file or directory, not going to touch it!"
			fi
		else
			# doesn't exist, make the link!
			echo "creating symlink ~/$i -> ~/.dotfiles/$i"
			ln -s ~/.dotfiles/$i ~/$i || echo "unable to create symlink ~/$i -> ~/.dotfiles/$i"
		fi
	fi
done
shopt -u dotglob

# .ssh files need to be done spiffylike, and we'll just smash what's already there, if anything
test -d ~/.ssh || mkdir -m 0700 ~/.ssh
curl -s https://github.com/kitchen.keys > ~/.dotfiles/.ssh/authorized_keys
ln -sf ~/.dotfiles/.ssh/authorized_keys ~/.ssh/authorized_keys || echo "unable to create .ssh/authorized_keys symlink, eek!"

# because mac-specific things and because Match and Include are only in later ssh versions
# hopefully this is just a temporary hack and I'll be removing it after all of the remote hosts I use
# get upgraded to later versions of software (dreamhost, I'm looking at you!)
rm ~/.ssh/config
cat ~/.dotfiles/.ssh/config.d/common > ~/.ssh/config
if [ "$(uname)" == "Darwin" ]; then
	cat ~/.dotfiles/.ssh/config.d/Darwin >> ~/.ssh/config
fi

if [[ -d ~/cozy ]]; then
	cat ~/.dotfiles/.ssh/config.d/cozy >> ~/.ssh/config
fi
