prompt_order = [
    "time",
    "username",
    "hostname",
    "directory",

    "git_branch",
    "git_commit",
    "git_state",
    "git_status",


    # modules maybe I use or not, but order not really important
    "kubernetes",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "erlang",
    "golang",
    "haskell",
    "java",
    "julia",
    "nim",
    "nodejs",
    "ocaml",
    "php",
    "purescript",
    "python",
    "ruby",
    "rust",
    "terraform",
    "zig",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "custom",

# not actually bright yellow with solarized

    "line_break",
    "battery",

    "jobs",
    "character"

]

[time]
disabled = false
style = "red"

[username]
# not actually bright yellow with solarized
style_user = "bright-yellow"

[hostname]
# not actually bright yellow with solarized
style = "bright-yellow"

[aws]
displayed_items = "profile"

