antigen bundle kubectl

export SPACESHIP_KUBECONTEXT_COLOR_GROUPS=(
	green 'minikube'
)
export SPACESHIP_KUBECONTEXT_PREFIX=" :: "
export SPACESHIP_KUBECONTEXT_SYMBOL=""
export SPACESHIP_KUBECONTEXT_PREFIX="kube: "
